services:
  - type: web
    name: grocery-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn djangoProject.wsgi:application"
    branch: main
    plan: free
